# A reusable workflow setup for testing the UI elements of the surveysaurus app
# Gets automatically triggered by surveysaurus-ui workflows

name: TestTheUI


on:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install selenium
        run: pip install selenium==4.4.0
        
      - name: Upgrade selenium
        run: pip3 install -U selenium
        
      - name: Install webdriver-manager
        run: pip install webdriver-manager
         
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -f 3 -d ' ' | cut -d '.' -f 1) \
          && CHROMEDRIVER_RELEASE=$(curl --location --fail --retry 3 http://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}) \
          && curl --silent --show-error --location --fail --retry 3 --output /tmp/chromedriver_linux64.zip "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_RELEASE/chromedriver_linux64.zip" \
          && cd /tmp \
          && unzip chromedriver_linux64.zip \
          && rm -rf chromedriver_linux64.zip \
          && sudo mv chromedriver /usr/local/bin/chromedriver \
          && sudo chmod +x /usr/local/bin/chromedriver \
          && chromedriver --version   
                          
      - name: Installed package list
        run: apt list --installed
                   
      - name: Run the test script
        run: python SurveySaurusLogin1.py production
 


